name: "CF Build and Deploy Action"
description: "This action deploys a project to IBM Cloud Foundry using the IBM Cloud CLI"
inputs:
  github-sha:
    description: "GitHub SHA value"
    required: true
  ibm-cloud-api-key:
    description: "IBM Cloud API Key, create one here - https://cloud.ibm.com/iam/apikeys"
    required: true
  ibm-cloud-org:
    description: "IBM Cloud Organization, normally your IBM Cloud username"
    required: false
    default: ""
  ibm-cloud-resource-group:
    description: "IBM Cloud Resource Group"
    required: false
    default: "default"
  ibm-cloud-region:
    description: "IBM Cloud Region"
    required: false
    default: "us-south"
  ibm-cloud-space:
    description: "IBM Cloud Space"
    required: false
    default: "dev"
  working-directory:
    description: "Working directory that contains a Dockerfile"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - id: install-ibmcloud-cli
      name: Install IBM CLI
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud --version
        ibmcloud config --check-version=false
      shell: bash
    
    - id: install-plugin-cf
      name: Install CF plugin
        run: ibmcloud cf install -f
        shell: bash

    - id: login-to-ibmcloud-cli
      run: |
        ibmcloud login --apikey "$IBM_CLOUD_API" -r "$IBM_CLOUD_REGION" -g "$IBM_CLOUD_GROUP"
      shell: bash
    
    - id: target-cf
      name: Target CF
        run: ibmcloud target --cf-api https://api.$IBM_CLOUD_REGION.cf.cloud.ibm.com -r $IBM_CLOUD_REGION -o $IBM_CLOUD_ORG -s $IBM_CLOUD_SPACE
        shell: bash
    
    - id: list-all-apps
      name: List all applications
        run: ibmcloud cf apps
        shell: bash

    - id: deploy-manifest
      name: Deploy manifest file
      run: ibmcloud cf push -f ./$MANIFEST_NAME
      shell: bash